In [1]:
# Q1.Write a Python program to print the NumPy version in your system.

#importing the numpy module as np
import numpy as np
print(np.__version__)

1.19.2


In [74]:
# Q2. Write a Python program to reverse an array (first element becomes last).
# Note : The flip fn will reverse the arry but the sort fn will arrange the item according to accending order

arr = np.arange(1,25)
print(arr)
print()
print(np.flip(arr))

print()

# fliping or reversing the 2 day array,
b = np.arange(1,26).reshape(5,5)
print(b)
print()
np.flip(b)

# when flip(array name, axis=0) the rows will get flip the top come bottom and bottom move to top.
# when flip(array name, axis=1) the clos will get flip the left cols will go right and vice versa. 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]



array([[25, 24, 23, 22, 21],
       [20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [85]:
# Q3. Write a Python program to convert a list and tuple into arrays.
a = [10,20,30,40]
print(np.array(a))
print()



#Case -2 nested list-01
lis = [[1,2,3],[4,5,6]]
print(np.array(lis))
print()

#case - 3 Nested list-02
a = [10,20,30,[88,99],40]
b = np.array(a)
print(b)
print(type(b))
print()


# Tuple into array
tup = (11,22,33,44)
print(np.array(tup))



[10 20 30 40]

[[1 2 3]
 [4 5 6]]

[10 20 30 list([88, 99]) 40]
<class 'numpy.ndarray'>

[11 22 33 44]


<ipython-input-85-0a604447e594>:15: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  b = np.array(a)


In [92]:
# Q4. Write a Python program to find common values between two arrays.
a = np.random.randint(1,26, (5,5))
print(a)
print()

b  = np.random.randint(1,26, (5,5))
print(b)
print()

#Finding the common value using built in fn. 
np.intersect1d(a,b)

[[12 19  7 15 14]
 [ 7 23 23  3 15]
 [19 17 18 15 14]
 [22 11 10 23 24]
 [11 25  5 10 15]]

[[19 18  1  2 14]
 [ 8 25  3 16  7]
 [24 10 15 17 18]
 [ 8  2 22  9 14]
 [13  1 16  7  8]]



array([ 3,  7, 10, 14, 15, 17, 18, 19, 22, 24, 25])

In [104]:
# Q5. Write a Python program compare two arrays using numpy.
#When doing the comp the rows and cols need to match. If not we get an error. 
a = np.random.randint(1,26, (5,5))
print(a)
print()

b  = np.random.randint(1,26, (5,5))
print(b)
print()

# Compaing two arrays.when the values get match we can find the o/p in boolen form.
print(a == b

[[14  4 23  9 12]
 [15 11  8 14 11]
 [ 1 14 18 19  7]
 [24 20  9 20 14]
 [ 6 18 16 11 16]]

[[24  4  2 21  3]
 [ 8 11 11 19 20]
 [17  8 16 10  5]
 [17 14 18 16 15]
 [25 25  9 19  9]]

[[False  True False False False]
 [False  True False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [114]:
# Q6.  Write a Python program to change the dimension of an array.
arr1 =  np.arange(1,21)
print('1d array: ', arr1)
print()

# Changing the dim 1d to 2d

b = arr1.reshape(4,5)
print(b)
print()

# 1D to 3D array
c = arr1.reshape(5,2,2)
print(c)

1d array:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]]


In [82]:
# Q7. Write a Python program (using numpy) to sum of all the multiples of 3 or 5 below 100.

# Case - 1
x = np.arange(1, 100)
# find multiple of 3 or 5
n= x[(x % 3 == 0) | (x % 5 == 0)]
print(n[:1000])
# print sum the numbers
print(n.sum())



# case -2
arr1 = np.arange(1,100)
arr1

count = 0

for i in arr1:
    if i%3 == 0:
        count += i
print('The sum of mupltiple of 3 from 1 to 99: ', count)
print()

# using filter method (Case -3)
arr1 = np.arange(1,100)
arr1

print(sum(list(filter(lambda i: i%3 == 0, arr1))))

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318
The sum of mupltiple of 3 from 1 to 99:  1683

1683


In [9]:
# Q8.Write a Python program to convert a NumPy array into Python list structure.
a = np.arange(1,11).reshape(2,5)
a
print(list(a))
print()

# Using the inbuilt function
x= np.arange(6).reshape(3, 2)
print("Original array elements:")
print(x)
print("Array to list:")
print(x.tolist())

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


[[0, 1], [2, 3], [4, 5]]

In [23]:
# Q9. Write a Python program to how to add an extra column to a numpy array.
x = np.array([[10,20,30], [40,50,60]])
y = np.array([[100], [200]])
print(np.append(x, y, axis=1))    #When we pass list in this format [ ], [ ] each list define coloumn. 

[[ 10  20  30 100]
 [ 40  50  60 200]]


In [38]:
# Q10. Write a Python program to check whether the numpy array is empty or not.
arr = np.empty((3,2))
arr1 = np.array([])
print(np.size(arr))
np.size(arr1)           #-------> The size fn help know number of elements of arry (Row X cols)
                                # The shape fn will help to know the shape nuumber rows and cols. 

6


0

In [41]:
# Q11. Write a Python program to normalize a 3x3 random matrix.
x= np.random.random((3,3))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.59771376 0.66475052 0.33517486]
 [0.81097418 0.00620479 0.90533831]
 [0.46803919 0.41445887 0.62801475]]
After normalization:
[[0.65786556 0.73242262 0.36587455]
 [0.89504992 0.         1.        ]
 [0.51364384 0.45405278 0.69156576]]


In [62]:
# Q12. How to swap two rows of an array?
A = np.arange(25).reshape(5,5)
print(A)
print()
A[[0,1]] = A[[1,0]]
print(A)
print()

# Inversing the array (Row into cols and cols into row)
a = np.arange(1,13).reshape(4,3)
print('Before Inversing')
print(a)
print()

print('After inversing')
a.T

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Before Inversing
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

After inversing


array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [64]:
# Q13. Python program to create a random vector of size 10 and sort it.
x = np.random.random(10)
print("Original array:")
print(x)
print()
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.90886009 0.43620666 0.43140948 0.7523842  0.00631973 0.25947183
 0.12312869 0.61835166 0.84759111 0.31434919]

Sorted array:
[0.00631973 0.12312869 0.25947183 0.31434919 0.43140948 0.43620666
 0.61835166 0.7523842  0.84759111 0.90886009]


In [66]:
# Q14. Write a Python program to check two random arrays are equal or not.
x = np.random.randint(0,2,6)
print("First array:")
print(x)
print()
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print()
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 0 0 1 1 0]

Second array:
[1 1 0 1 1 0]

Test above two arrays are equal or not!
False


In [77]:
# Q15. Write a Python program to add, subtract, multiply, divide arguments element-wise.
print("Add:")
print(np.add(1, 4))
print("Subtract:")
print(np.subtract(1.0, 4.0))
print("Multiply:")
print(np.multiply(1.0, 4.0))
print("Divide:")
print(np.divide(1.0, 4.0))
print()

a = np.random.randint(1,15, (3,3))
b = np.random.randint(5, 15, (3,3))
print(a)
print()
print(b)
print()
print('Adding 2d arrays')
print(np.add(a,b))

Add:
5
Subtract:
-3.0
Multiply:
4.0
Divide:
0.25

[[ 8  9  8]
 [ 3  5 12]
 [ 4 11  2]]

[[ 8  5 12]
 [ 9 14  9]
 [ 8 11 11]]

Adding 2d arrays
[[16 14 20]
 [12 19 21]
 [12 22 13]]


In [78]:
# Q16. Write a Python program to get the dates of yesterday, today and tomorrow.
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1,
'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2021-07-12
Today:  2021-07-13
Tomorrow:  2021-07-14


In [79]:
#Q17. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e.,
#resample the elements of an array with replacement N times, compute the mean of each sample,and then compute percentiles
# over the means).
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.24952597  0.11598346]
